#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

mkdir -p "$tmp/bin"
cat > "$tmp/bin/psql" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
printf '%s\n' "$@" > "$PSQL_ARGS_LOG"
cat > "$PSQL_STDIN_LOG"
EOF
chmod +x "$tmp/bin/psql"

# These fixtures verify shell argument boundaries only. Production passwords use
# the URL-safe hexadecimal format generated by `openssl rand -hex 32`.
migration_password="migration secret with ' apostrophe"
runtime_password="runtime secret with ' apostrophe"
backup_password="backup secret with ' apostrophe"

output="$({
  PATH="$tmp/bin:$PATH" \
  PSQL_ARGS_LOG="$tmp/psql-args.log" \
  PSQL_STDIN_LOG="$tmp/psql-stdin.log" \
  POSTGRES_USER=postgres \
  POSTGRES_DB=overtime \
  POSTGRES_MIGRATION_PASSWORD="$migration_password" \
  POSTGRES_RUNTIME_PASSWORD="$runtime_password" \
  POSTGRES_BACKUP_PASSWORD="$backup_password" \
    "$root/docker/postgres/init-roles.sh"
} 2>&1)"

for secret in "$migration_password" "$runtime_password" "$backup_password"; do
  if [[ "$output" == *"$secret"* ]]; then
    echo 'role bootstrap printed a password' >&2
    exit 1
  fi
done

grep -Fqx -- "--set=migrator_password=migration secret with ' apostrophe" "$tmp/psql-args.log"
grep -Fqx -- "--set=runtime_password=runtime secret with ' apostrophe" "$tmp/psql-args.log"
grep -Fqx -- "--set=backup_password=backup secret with ' apostrophe" "$tmp/psql-args.log"
grep -Fqx -- '--set=ON_ERROR_STOP=1' "$tmp/psql-args.log"

grep -Fxq 'BEGIN;' "$tmp/psql-stdin.log"
grep -F 'CREATE ROLE overtime_migrator LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE' "$tmp/psql-stdin.log"
grep -F 'CREATE ROLE overtime_app LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE' "$tmp/psql-stdin.log"
grep -F 'CREATE ROLE overtime_backup LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE' "$tmp/psql-stdin.log"
grep -F 'ALTER DATABASE :"database_name" OWNER TO overtime_migrator' "$tmp/psql-stdin.log"
grep -F 'ALTER SCHEMA public OWNER TO overtime_migrator' "$tmp/psql-stdin.log"
grep -F 'GRANT CONNECT ON DATABASE :"database_name" TO overtime_app, overtime_backup' "$tmp/psql-stdin.log"
grep -F 'GRANT USAGE ON SCHEMA public TO overtime_app, overtime_backup' "$tmp/psql-stdin.log"
grep -F 'GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO overtime_app' "$tmp/psql-stdin.log"
grep -F 'GRANT SELECT ON TABLES TO overtime_backup' "$tmp/psql-stdin.log"
grep -Fxq 'COMMIT;' "$tmp/psql-stdin.log"

begin_line="$(grep -nFx 'BEGIN;' "$tmp/psql-stdin.log" | cut -d: -f1)"
first_role_line="$(grep -nF 'CREATE ROLE overtime_migrator' "$tmp/psql-stdin.log" | cut -d: -f1)"
commit_line="$(grep -nFx 'COMMIT;' "$tmp/psql-stdin.log" | cut -d: -f1)"
(( begin_line < first_role_line && first_role_line < commit_line ))

echo 'postgres role bootstrap contract passed'
